global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'porttrack-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['porttrack-staging.example.com:8080', 'porttrack-prod.example.com:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8081']